### PR TITLE
Fix NumPy float and int

### PR DESCRIPTION
**Pull request by erikkjellgren**
`np.float` and `np.int` does not exist in NumPy anymore.

Code changed to use `np.float64` and `np.int64`.

### CODE REVIEW

**Comment by kottmanj** [comment]
Hi Eric, 
thanks for contributing!
Looks like we forgot some of the np.floats in #287
In order to avoid circular PRs that change the types. Would changing from `np.float` to just `float` (instead of `np.float64`) also suffice? Just to stay consistent with the rest.

**Comment by kottmanj** [comment]
Perfect!
Could you change it in the PR here? Then I can just merge this one.

**Comment by erikkjellgren** [comment]
I have already pushed the changes.

A little unrelated note.
In `src/tequila/optimizers/optimizer_phoenics.py` line 93 the type used is `np.float32`, I think this is the only place in the entire Tequila code that np.float32 is used, this could be a typo.

**Comment by kottmanj** [comment]
True. Thanks for noticing!

**Pull request merged**
